#!/usr/bin/env python

import argparse
import getpass
import os.path
from pathlib import Path

import utils

HERE = Path(os.path.dirname(__file__))

PARSER = argparse.ArgumentParser('Get a password')
PARSER.add_argument("name")

args = PARSER.parse_args()
master = getpass.getpass()

with (HERE / (args.name + ".pass")).open() as f:
    encrypted = f.read()

print(utils.decrypt(master, encrypted))








