#!/usr/bin/env python

import argparse
import getpass
import os.path
from pathlib import Path

from xkcdpass import xkcd_password

import utils

HERE = Path(os.path.dirname(__file__))

PARSER = argparse.ArgumentParser('Create a new password')
PARSER.add_argument("name")

args = PARSER.parse_args()
master = getpass.getpass("master password")

password_file = HERE / (args.name + ".pass")

if password_file.exists():
    raise Exception(f"{password_file} already exists")

new_password = xkcd_password.generate_xkcdpassword(xkcd_password.generate_wordlist(), delimiter=".", numwords=5)
cipher = utils.encrypt(master, new_password)

with (password_file).open("w") as f:
    plain = f.write(cipher)

